export { Page } from './Page';
export { Page as P } from './Page';
export { Wrapped } from './Wrapped';
export { Wrapped as W } from './Wrapped';
export { Text } from './Text';
export { Text as T } from './Text';
export { Linear } from './Linear';
export { Linear as L } from './Linear';
export { Icon } from './Icon';
export { Icon as I } from './Icon';
